dependencies:
  - python
  - pip
  - numpy
  - pandas
  - geopandas
  - jupyterlab
  - hvplot
  - jupyter_bokeh
  - matplotlib
  - geoviews
  - cartopy
  - bokeh
  - dask
  - odc-stac
  - planetary-computer
  - pystac-client
  - fsspec
  - gdown
  - aiohttp
  - scipy
  - xarray
  - netcdf4
  - rioxarray
  - opencv
  - folium
  - distributed
  - zarr
  - tqdm
  - nb_conda_kernels
  - black
  - flake8
  - earthaccess
  - hydroerr
  - nodejs
  - earthengine-api
  - earthaccess
  - pytest
  - conda-build
  - coverage
  - lxml
  - geemap
  - tensorflow
  - altair
  - ca-certificates
  - certifi
  - openssl
  - scikit-learn
  - selenium
  - firefox
  - geckodriver
  - sentinelsat
  - netcdf4
  - packaging
  - vegafusion-python-embed
  - vl-convert-python
  - papermill
  - jupyter