dependencies:
  - python
  - pip
  - numpy
  - pandas
  - geopandas
  - jupyterlab
  - hvplot
  - jupyter_bokeh
  - matplotlib
  - geoviews
  - cartopy
  - bokeh
  - dask
  - odc-stac
  - jupyterlab
  - planetary-computer
  - pystac-client
  # temp
  - awscli
  - s3fs
  - fsspec
  - gdown
  - aiohttp
  - scipy
  - xarray
  - rioxarray
  - opencv
  - folium
  - distributed
  - zarr
  - tqdm
  - nb_conda_kernels
  - black
  - flake8
  - hydroerr
  - earthaccess
  - earthengine-api
  - nodejs
  - pytest
  - conda-build
  # pekel dataset
  - pip:
    - dask-labextension
    - podaac-data-subscriber
    - download_water_data
