dependencies:
  - python
  - pip
  - numpy
  - pandas
  - geopandas
  - dask
  - odc-stac
  - planetary-computer
  - pystac-client
  - fsspec
  - gdown
  - aiohttp
  - scipy
  - xarray
  - netcdf4
  - rioxarray
  - distributed
  - tqdm
  - hydroerr
  - earthengine-api
  - earthaccess
  - pytest
  - conda-build
  - coverage
  - lxml
  - tensorflow
  - packaging
  - pip:
    - podaac-data-subscriber